# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0003_auto_20170511_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('S', 'Subjective'), ('O', 'Objective')], default='S', max_length=1),
        ),
    ]
