# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0005_auto_20170511_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQusetionOptionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_qusetion_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_manager.FeedbackQusetionMap')),
                ('submitted_option', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='submited_option', to='feedback_manager.Option')),
            ],
        ),
    ]
